spring:
  application:
    name: barber-shop-api
  datasource:
    url: jdbc:mysql://localhost:3306/db_barber_shop
    username: root
    password: ghostsandme
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    url: jdbc:mysql://localhost:3306/db_barber_shop
    user: root
    password: ghostsandme
    locations: classpath:db/migration
    validate-on-migrate: false